### PR TITLE
go mod init && go mod vendor

### PR DESCRIPTION
**Pull request by xujintao**
we should provide vendor for those who cannot get(go get) essential packages on which go-shadowsocks2 depending from golang.org.

### CODE REVIEW

**Comment by mritd** [comment]
I don't think it's necessary to add the vendor directory because go mod seems to do the same thing.

**Comment by xujintao** [comment]
The meaning of vendor directory is avoid downloading some dependence from some repository which has been prevent by GFW. 
Alternatively, we can get the same effect with dep.

**Comment by Flandoll** [comment]
Should be able to replace `golang.org/x/...` with `github.com/golang/...` with go mod `replace` directive
[https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive](url)

**Comment by xujintao** [comment]
@Flandoll yes, replace is better for there are only 2 dependence from golang.org/x/xxx

**Comment by xujintao** [comment]
@riobard 
In fact, it has nothing to do with go modules, but the vendor directory or the dependency.
For example, i want to build a special [docker image](https://github.com/xujintao/deven/tree/master/ss), so i need git clone the src first:
```shell
git clone https://github.com/xujintao/go-shadowsocks2.git $GOPATH/src/github.com/shadowsocks/go-shadowsocks2
go build github.com/shadowsocks/go-shadowsocks2
```
This will result in failure for lack of dependency of golang.org/x/...

**Comment by xujintao** [comment]
@mritd 
Good idea. But that could be the result before which i may have to keep debugging locally until it work right :joy:

**Comment by riobard** [comment]
I think we've had support for Go modules now. Closing unless there's more to discuss.

**Pull request closed without merging**
