### PR TITLE
Change shadowsocks2 -> go-shadowsocks2

### PR DESCRIPTION
**Pull request by kazhuravlev**
After `go get` program will have name `go-shadowsocks2`

### CODE REVIEW

**Comment by riobard** [comment]
Yeah… I'm a little divided by this. The released binaries are all called `shadowsocks2`, but you're right that if you `go get` it would keep the repo name…

**Comment by mritd** [comment]
> Yeah… I'm a little divided by this. The released binaries are all called `shadowsocks2`, but you're right that if you `go get` it would keep the repo name…

Should the command in dockerfile also use shadowsocks2? 
refs PR #122

**Comment by riobard** [comment]
I don't know. Maybe @kazhuravlev is right and it should be called go-shadowsocks2 because `shadowsocks2` might be used by the Python implementation if they want to do a major rewrite 😄

**Comment by mritd** [comment]
I think the project name can be`go-shadowsocks2`, but the command name is more convenient to use with `shadowsocks`. 😂

**Comment by riobard** [comment]
@mritd Yes, or maybe all implementations can use the same binary name, just like MariaDB still installs `mysql` 😂

**Pull request merged**
