### PR TITLE
New feature: Support multiple servers setup

### PR DESCRIPTION
**Pull request by namaho**
Then we can have two servers, listening on their own port, like this:
```
go-shadowsocks2 -s ss://AEAD_CHACHA20_POLY1305:your-password@:8488  -s ss://AEAD_CHACHA20_POLY1305:another-password@:8489 -verbose
```

How do you think about this feature?

Maybe we should update README if this PR got merge.

### CODE REVIEW

**Comment by riobard** [comment]
This is unlikely the direction forward. Listening on multiple port is a hack due to lack of support for true multiuser mode. Please see https://github.com/shadowsocks/shadowsocks-org/issues/54 for further discussion.

**Comment by namaho** [comment]
YES, this is absolutely not the correct way to support multi-user in large scale deployment, and not for the `Next-generation` Shadowsocks.

But I think we should at least support such a feature to meet the needs of most people at the moment, since the `Next-generation` SPEC haven't yet finalized, and has no client support.

Or another branch for this feature?

**Comment by riobard** [comment]
Currently you can run multiple server instances each listening on a different port for smaller scale deployment. I don't see a pressing need for the change.

**Comment by namaho** [comment]
Okay, have another process is also the work way. I will close the PR.

**Pull request closed without merging**
